In [1]:
import torch
from nesvor.image import *
from nesvor.transform import *
from scipy.spatial.transform import Rotation as R
stacks = torch.load("stacks_test_angle.pth")
stacks

In [2]:
stacks[0].transformation.mean().axisangle()

tensor([[  1.0633,  -1.4424,   1.2849,  22.7985,  18.6597, -27.8910]],
       device='cuda:0')

## Stack 1 


In [3]:
from nesvor.transform.transform import *
print("angles using provided method:")
print(mat2euler(stacks[0].transformation.mean().matrix())[..., -3:])
print("angles using scipy:")
print(R.from_matrix(stacks[0].transformation.mean().matrix().cpu()[..., :3]).as_euler("xyz", degrees=True))
print("actual angles:", stacks[0].rot_angles * 180 / np.pi)

angles using provided method:
tensor([[ -92.9796,    4.5548, -102.8804]], device='cuda:0')
angles using scipy:
[[-103.33543194  -77.01773737 -171.55461209]]
actual angles: tensor([90.,  0.,  0.])


## Stack 2


In [4]:
print("angles using provided method:")
print(mat2euler(stacks[1].transformation.mean().matrix())[..., -3:])
print("angles using scipy:")
print(R.from_matrix(stacks[1].transformation.mean().matrix().cpu()[..., :3]).as_euler("xyz", degrees=True))
print("actual angles:", stacks[1].rot_angles * 180 / np.pi)

angles using provided method:
tensor([[10.1608, 12.1093,  6.2612]], device='cuda:0')
angles using scipy:
[[ -9.02363169 -12.97320492  -4.15261255]]
actual angles: tensor([  0.0000, 180.0000,   0.0000])


## Stack 3

In [5]:
print("angles using provided method:")
print(mat2euler(stacks[2].transformation.mean().matrix())[..., -3:])
print("angles using scipy:")
print(R.from_matrix(stacks[2].transformation.mean().matrix().cpu()[..., :3]).as_euler("xyz", degrees=True))
print("actual angles:", stacks[2].rot_angles * 180 / np.pi)

angles using provided method:
tensor([[158.0700,  84.4000,  66.3179]], device='cuda:0')
angles using scipy:
[[-95.19583916   1.65015977  87.75274959]]
actual angles: tensor([ 0.,  0., 90.])


# Ridiculous! 😅